# Generated by Django 4.0.1 on 2022-01-31 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AddField(
            model_name='task',
            name='coment',
            field=models.CharField(default='Sin comentarios', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('T', 'ToDo'), ('I', 'In Progres'), ('D', 'Done'), ('C', 'Close')], default='T', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(max_length=300),
        ),
    ]
