# Generated by Django 4.0.1 on 2022-01-31 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_task_autor_alter_task_task_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='autor',
            new_name='user',
        ),
    ]
