# Generated by Django 4.0.1 on 2022-01-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_rename_autor_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
